import assert from 'node:assert/strict';
import {orderedQuestions} from '../dist/questions.js';
import {newGame,applyAnswer,feedback} from './quiz-rules.js';
import {legacyQuestions} from './legacy-questions.js';
import {createPracticeGame} from '../dist/practice-game.js';
const body=(q,value=q.answer)=>({questionId:q.id,choice:q.options.indexOf(value),value,elapsedMs:9900});
const first=orderedQuestions[0];
const existing=newGame('existing','hash','Nombre',3,1000);delete existing.bank_version;existing.cursor=1;
applyAnswer(existing,body(legacyQuestions[1]),1100);
assert.equal(feedback(existing).question.text,legacyQuestions[1].question,'An existing game keeps its bank and correction after questions are reordered');
assert.equal(existing.score,1);assert.equal(existing.lives,10);
let game=newGame('id','hash','Nombre',3,1000);
applyAnswer(game,body(first),11900);
assert.equal(game.last_correct,1,'A choice sent before ten seconds survives a bounded delivery delay');
assert.equal(feedback(game).acceptedValue,first.answer);
game=newGame('id','hash','Nombre',3,1000);
applyAnswer(game,body(first),13001);assert.equal(game.last_reason,'timeout','Delivery grace is bounded');
game=newGame('id','hash','Nombre',3,1000);
applyAnswer(game,{...body(first),elapsedMs:10000},11000);assert.equal(game.last_reason,'timeout','A late tap cannot be accepted');
let now=0;const practice=createPracticeGame(()=>now);
const referee=orderedQuestions.find(q=>q.id===49),number=orderedQuestions.indexOf(referee)+1;
let q=practice('start',{number});assert.equal(q.number,number);assert.equal(q.score,0);
const wrong=referee.options.find(v=>v!==referee.answer);
const r=practice('answer',body(referee,wrong));assert.equal(r.correct,false);assert.equal(r.lives,9);assert.equal(r.score,0);assert.equal(r.acceptedValue,wrong);
now+=120000;assert.equal(practice('state').lives,9);assert.equal(practice('answer',body(referee)).lives,9);
q=practice('next');assert.equal(q.number,number+1);assert.equal(q.remainingMs,10000);
now+=10000;assert.equal(practice('answer',{questionId:q.question.id,choice:null}).lastReason,'timeout');
for(const option of orderedQuestions.at(-1).options){q=practice('start',{number:125});now+=60000;const final=practice('answer',body(orderedQuestions.at(-1),option));assert.equal(final.phase,'done');assert.equal(final.score,1);assert.equal(final.lives,10);}
assert.throws(()=>practice('start',{number:126}));assert.throws(()=>practice('leaderboard'));
console.log('Entrega tardía acotada, elección registrada, pausa, vidas y cuatro cierres del modo de prueba verificados.');
